[package]
name = "cao_app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cao_core = { path = "../core" }
cao_render = { path = "../render" }
eframe.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
glam.workspace = true
wgpu.workspace = true

[[bin]]
name = "cao"
path = "src/main.rs"
