[package]
name = "cao_app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cao_part = { path = "../part" }
cao_prefs = { path = "../prefs" }
cao_render = { path = "../render" }
cao_sketch = { path = "../sketch" }
cao_solid = { path = "../solid" }
chrono.workspace = true
eframe.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
glam.workspace = true
wgpu.workspace = true

[dev-dependencies]
cao_part = { path = "../part", features = ["test-support"] }
cao_prefs = { path = "../prefs", features = ["test-support"] }

[[bin]]
name = "cao"
path = "src/main.rs"
